#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The YugabyteDB database container.
  yugabytedb:
    # https://hub.docker.com/r/yugabytedb/yugabyte
    image: yugabytedb/yugabyte:latest
    container_name: "${YUGABYTEDB_CONTAINER_NAME:-yugabytedb}"
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${YUGABYTEDB_YSQL_PORT:-5433}:5433
     - ${YUGABYTEDB_YCQL_PORT:-9042}:9042
    # Admin UI
     - ${YUGABYTEDB_MASTER_PORT:-7001}:7000
     - ${YUGABYTEDB_TSERVER_PORT:-9000}:9000
    volumes:
      - yugabytedb_data:/home/yugabyte/yb_data
    command: [
      "bin/yugabyted", "start",
      "--base_dir=/home/yugabyte/yb_data",
      "--daemon=false"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  yugabytedb_data:
    driver: "local"
    name: "${YUGABYTEDB_CONTAINER_NAME:-yugabytedb}_data"
