#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The MySQL database container.
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:latest
    container_name: "${MYSQL_CONTAINER_NAME:-mysql}"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - local
    # Enable platform for Apple Silicon.
    platform: linux/x86_64
    # Map the database container exposed port to the host port.
    ports:
     - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    # Use mysql_native_password instead of caching_sha2_password
    # command: "--default-authentication-plugin=mysql_native_password"

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  mysql_data:
    driver: "local"
    name: "${MYSQL_CONTAINER_NAME:-mysql}_data"
