#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Neo4j database container.
  neo4j:
    # https://hub.docker.com/_/neo4j
    image: neo4j:latest
    container_name: "${NEO4J_CONTAINER_NAME:-neo4j}"
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${NEO4J_PORT:-7474}:7474
     - ${NEO4J_BOLT_PORT:-7687}:7687
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  neo4j_data:
    driver: "local"
    name: "${NEO4J_CONTAINER_NAME:-neo4j}_data"
  neo4j_logs:
    driver: "local"
    name: "${NEO4J_CONTAINER_NAME:-neo4j}_logs"
