#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The SurrealDB database container.
  surrealdb:
    # https://hub.docker.com/r/surrealdb/surrealdb
    image: surrealdb/surrealdb:latest
    container_name: "${SURREALDB_CONTAINER_NAME:-surrealdb}"
    networks:
      - local
    ports:
     - ${SURREALDB_PORT:-8000}:8000
    volumes:
      - surrealdb_data:/data/db
    command: [
      "start",
      "--log", "full",
      "--user", "${SURREALDB_USERNAME}",
      "--pass", "${SURREALDB_PASSWORD}",
      "file:/data/db"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  surrealdb_data:
    driver: "local"
    name: "${SURREALDB_CONTAINER_NAME:-surrealdb}_data"
