# Docker compose version https://docs.docker.com/compose/compose-file
version: '3.8'

# Docker services
services:
  # Database container
  mssql:
    container_name: "${MSSQL_CONTAINER_NAME:-mssql}"
    # https://hub.docker.com/_/microsoft-mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_ROOT_PASSWORD}"
    networks:
      - local
    ports:
     - "${MSSQL_PORT:-1433}:1433"
    volumes:
      - mssql_data:/var/opt/mssql

# Docker networks
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# Docker volumes
volumes:
  mssql_data:
    driver: "local"
    name: "${MSSQL_CONTAINER_NAME:-mssql}_data"
