# Docker compose version https://docs.docker.com/compose/compose-file
version: '3.8'

# Docker services
services:
  # Database container
  mariadb:
    container_name: "${MARIADB_CONTAINER_NAME:-mariadb}"
    # https://hub.docker.com/_/mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USERNAME}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    networks:
      - local
    ports:
     - "${MARIADB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MARIADB_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s

# Docker networks
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# Docker volumes
volumes:
  mariadb_data:
    driver: "local"
    name: "${MARIADB_CONTAINER_NAME:-mariadb}_data"
