# Docker compose version https://docs.docker.com/compose/compose-file
version: '3.8'

# Docker services
services:
  # MongoDB container
  mongodb:
    container_name: "${MONGO_CONTAINER_NAME:-mongodb}"
    # https://hub.docker.com/_/mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - local
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      retries: 3
      timeout: 5s

# Docker networks
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# Docker volumes
volumes:
  mongodb_data:
    driver: "local"
    name: "${MONGO_CONTAINER_NAME:-mongodb}_data"
