# Docker compose version https://docs.docker.com/compose/compose-file
version: '3.8'

# Docker services
services:
  # Redis container
  redis:
    container_name: "${REDIS_CONTAINER_NAME:-redis}"
    # https://hub.docker.com/_/redis
    image: redis:alpine
    networks:
      - local
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

# Docker networks
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# Docker volumes
volumes:
  redis_data:
    driver: "local"
    name: "${REDIS_CONTAINER_NAME:-redis}_data"
