#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: localhost-databases

# The Docker services.
services:
  # The MongoDB database container.
  mongodb:
    # https://hub.docker.com/_/mongo
    image: mongo:latest
    container_name: "${DB_CONTAINER_NAME:-mongodb}"
    environment:
      MONGO_INITDB_DATABASE: "${DB_DATABASE:-local}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      retries: 3
      timeout: 5s
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  mongodb_config:
    driver: "local"
    name: "${DB_VOLUME_CONFIG_NAME:-mongodb_config}"
  mongodb_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-mongodb_data}"
