#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: localhost-databases

# The Docker services.
services:
  # The DynamoDB local database container.
  dynamodb:
    # https://hub.docker.com/r/amazon/dynamodb-local
    image: amazon/dynamodb-local:latest
    container_name: "${DB_CONTAINER_NAME:-dynamodb}"
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${DB_PORT:-8000}:8000
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  dynamodb_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-dynamodb_data}"
