blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/luisaveiro/localhost-databases/discussions/categories/q-a
    about: Ask the community for help
  - name: Feature Request
    url: https://github.com/luisaveiro/localhost-databases/discussions/categories/ideas
    about: Share ideas for new features
