#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: localhost-databases

# The Docker services.
services:
  # The Redis database container.
  redis:
    # https://hub.docker.com/_/redis
    image: redis:alpine
    container_name: "${DB_CONTAINER_NAME:-redis_db}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
      - ${DB_PORT:-6379}:6379
    volumes:
      - redis_db_data:/data

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  redis_db_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-redis_db_data}"
