#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Sets the project name.
name: localhost-databases

# The Docker services.
services:
  # The Microsoft SQL database container.
  mssql:
    # https://hub.docker.com/_/microsoft-mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "${DB_CONTAINER_NAME:-mssql_db}"
    environment:
      MSSQL_PID: "${MSSQL_PID:-Developer}"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${DB_PORT:-1433}:1433
    volumes:
      - mssql_db_data:/var/opt/mssql

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  mssql_db_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-mssql_db_data}"
