#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: localhost-databases

# The Docker services.
services:
  # The couchDB database container.
  couchdb:
    # https://hub.docker.com/_/couchdb
    image: couchdb:latest
    container_name: "${DB_CONTAINER_NAME:-couchdb}"
    environment:
      COUCHDB_USER: "${DB_USERNAME}"
      COUCHDB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - ${DB_PORT:-5984}:5984
    volumes:
      - couchdb_data:/opt/couchdb/data

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  couchdb_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-couchdb_data}"
